# Generated by Django 6.1 on 2026-08-23 09:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_name', models.CharField(max_length=120, verbose_name="owner's name")),
                ('owner_phone', models.CharField(max_length=20, verbose_name='contact number')),
                ('owner_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('vehicle_make', models.CharField(max_length=60)),
                ('vehicle_model', models.CharField(max_length=60)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('registration_number', models.CharField(max_length=20)),
                ('segment', models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV / MUV'), ('luxury', 'Luxury / imported')], default='hatchback', max_length=20)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('overall_severity', models.CharField(blank=True, choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('parts_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('labour_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paint_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('is_stub', models.BooleanField(default=False)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inspection',
                'verbose_name_plural': 'inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('scratch', 'Scratch'), ('dent', 'Dent'), ('crack', 'Crack'), ('lamp_broken', 'Broken lamp'), ('dislocated_part', 'Dislocated / missing part'), ('glass_shatter', 'Shattered glass'), ('tire_flat', 'Flat tyre')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('component', models.CharField(choices=[('front_bumper', 'Front bumper'), ('rear_bumper', 'Rear bumper'), ('bonnet', 'Bonnet / hood'), ('boot', 'Boot / tailgate'), ('roof', 'Roof'), ('front_fender', 'Front fender'), ('rear_fender', 'Rear fender / quarter'), ('front_door', 'Front door'), ('rear_door', 'Rear door'), ('windscreen', 'Windscreen'), ('rear_glass', 'Rear glass'), ('door_glass', 'Door glass'), ('headlamp', 'Headlamp'), ('taillamp', 'Taillamp'), ('grille', 'Front grille'), ('wheel', 'Wheel / tyre'), ('other', 'Other / unspecified')], max_length=20)),
                ('action', models.CharField(max_length=120)),
                ('instances', models.PositiveIntegerField(default=1)),
                ('part_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paint_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('labour_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='assessment.inspection')),
            ],
            options={
                'verbose_name': 'cost line',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.CharField(choices=[('front', 'Front'), ('front_left', 'Front left (3/4)'), ('left', 'Left side'), ('rear_left', 'Rear left (3/4)'), ('rear', 'Rear'), ('rear_right', 'Rear right (3/4)'), ('right', 'Right side'), ('front_right', 'Front right (3/4)'), ('roof', 'Roof'), ('closeup', 'Close-up of damage')], default='closeup', max_length=20)),
                ('panel', models.CharField(choices=[('front_bumper', 'Front bumper'), ('rear_bumper', 'Rear bumper'), ('bonnet', 'Bonnet / hood'), ('boot', 'Boot / tailgate'), ('roof', 'Roof'), ('front_fender', 'Front fender'), ('rear_fender', 'Rear fender / quarter'), ('front_door', 'Front door'), ('rear_door', 'Rear door'), ('windscreen', 'Windscreen'), ('rear_glass', 'Rear glass'), ('door_glass', 'Door glass'), ('headlamp', 'Headlamp'), ('taillamp', 'Taillamp'), ('grille', 'Front grille'), ('wheel', 'Wheel / tyre'), ('other', 'Other / unspecified')], default='other', max_length=20)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='annotated/%Y/%m/')),
                ('image_width', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('reference_area_px', models.FloatField(default=0.0)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assessment.inspection')),
            ],
            options={
                'verbose_name': 'photograph',
                'verbose_name_plural': 'photographs',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DamageDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('scratch', 'Scratch'), ('dent', 'Dent'), ('crack', 'Crack'), ('lamp_broken', 'Broken lamp'), ('dislocated_part', 'Dislocated / missing part'), ('glass_shatter', 'Shattered glass'), ('tire_flat', 'Flat tyre')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('confidence', models.FloatField()),
                ('area_px', models.FloatField()),
                ('area_fraction', models.FloatField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('x1', models.FloatField(default=0.0)),
                ('y1', models.FloatField(default=0.0)),
                ('x2', models.FloatField(default=0.0)),
                ('y2', models.FloatField(default=0.0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='assessment.vehicleimage')),
            ],
            options={
                'verbose_name': 'damage detection',
                'ordering': ['-area_fraction', 'class_name'],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['-created_at'], name='insp_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['registration_number'], name='insp_regno_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['owner_name'], name='insp_owner_idx'),
        ),
    ]
